# -*- coding: utf-8 -*-
"""Copy of Calculator(simple)ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FiZwGq27G9L1Yu6gREcQu9-emsBu_5Np
"""

num1 =input("Enter a number: ")
num2 =input("Enter another number: ")
result =float(num1)+float(num2)
print (result)